### PR TITLE
adding .app + using namecheap for .name

### PR DESCRIPTION
**Pull request by linuxjuggler**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 
| License       | MIT

1. NameCheap provides more/better information about the `.cloud` and `.name` domains
2. Also now we have `.app` domains which are controlled by google (without adding any tests)

### CODE REVIEW

**Comment by io-developer** [comment]
Oh, thanks for contribution!
Please set `whois.namecheap.com` as secondary whois and add primaries as `whois.nic.name` and  `whois.nic.cloud `

I'm checking it here - https://www.iana.org/domains/root/db

.name - https://www.iana.org/domains/root/db/name.html
.cloud - https://www.iana.org/domains/root/db/cloud.html

**Comment by io-developer** [comment]
Just for test I checked `some.cloud` and `whois.namecheap.com` response empty.

Default:
image

namecheap:
image

**Comment by linuxjuggler** [comment]
@io-developer done, I removed namecheap from `.cloud` I tested it with my own domain which I register by them, so maybe this is why I got a better answer.

Also, I changed the order as requested

**Comment by io-developer** [comment]
Thanks.

**Comment by io-developer** [comment]
Are you sure it's working?

image

Could do you provide your test info to check it out?

**Comment by linuxjuggler** [comment]
It is working from my end on both servers

Screen Shot 2019-08-15 at 1 53 46 PM

Screen Shot 2019-08-15 at 1 54 27 PM

If you want I can remove it too and just leave the `.app` server

**Comment by io-developer** [comment]
1. I guess your registrar provides own whois server. So these domains will have info. But others will not.
So yes, please remove this host for .name

2. I've got different response for your domain via whois.nic.name (via whois.namecheap.com all is ok) . Don't have idea why
image

**Comment by linuxjuggler** [comment]
1- Ok will do.
2- No idea, the way the whois providers works is killing me, I have built a small app to monitor the domain names expiration date using electron, and every day I need to deal with new issue, most of them related to the fact that each whois provider return a different information, or hide the information I need about the domains.

I'll update the commit and let you know.

Also, do you plan to add the registrar URL or I can create a new PR for it?

**Comment by io-developer** [comment]
Thanks.
Actually no plans. Could you describe some cases why registrar url is necessary?
Anyway you can do PR. But you have to update all tests data...

**Comment by linuxjuggler** [comment]
Knowing the registrar URL (when provided by the whois server) can help you remember which company you have used to register the domain, primarily when you use multiple companies.

**Comment by linuxjuggler** [comment]
@io-developer I think I know why whois.nic.name and whois.namecheap.com provide different values.

[whois.nic.name](https://webwhois.nic.name/DotNameWhois/pages/Query.jspx) has three types of information:
1. The Summary Results which is the default one.
2. The Standard Results provides information like the creation/expiration dates.
3. The Detailed Results which they request money to get access.

Since my domain was registered via namecheap the full information was provided by namecheap.

So right now I guess we need to figure out how to query whois.nic.name asking for the standard results, not the summary one. I am searching for an answer, but I thought it would be important to share what I found out with you, you may know something that can help.

**Comment by io-developer** [comment]
Actually some WHOISes (like for .com) provides whois referrer that contais full information.
Also I have seen from other hosts the 'whois: %whois.someregistar.com%' field in response.
I don't have idea is it possoble to push custom key-value into whois.nic.name or not..

**Comment by io-developer** [comment]
https://github.com/io-developer/php-whois/blob/master/tests/Iodev/Whois/Modules/Tld/parsing_data/.com/google.com.txt

**Comment by linuxjuggler** [comment]
True, but `whois.nic.name` provides the minimal data with the summary output https://who.is/whois/mhdzaherghaibeh.name

```
 Registry Domain ID: 134503878_DOMAIN_NAME-VRSN
 Domain Name: MHDZAHERGHAIBEH.NAME
 Registrar: NameCheap, Inc.
 Registrar IANA ID: 1068
 Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
```
which is annoying, cause not all providers expose everything. for example `.de` and `.pl` domains try to reduct as much information as they can.

**Comment by linuxjuggler** [comment]
Also, I was thinking if I added a server using the `addServers` function, why the results won't be merged?

for example like here in the `.name` situation, if I provided also another whois server, why the missing information won't be retrieved from the second server?

I know that I am annoying you ;) with my questions, but these are ideas I have which they might be good for the next version

**Comment by io-developer** [comment]
You should add `whois.namecheap.com` as first `.name` server in __your project__. Because it's very custom way.
In that case I guess it will work:
* querying `whois.namecheap.com` as first whois
* querying default servers if no info from previous

**Comment by linuxjuggler** [comment]
I'll check and get back to you.

Thanks man 👍

**Comment by io-developer** [comment]
Okay)

Also look at that:
image

Do you know some way to get registrar info by this ID? It can be a feature)

**Comment by linuxjuggler** [comment]
I'll look to see if I can find something here.

Also, what is the way to push `whois.namecheap.com` to be before `whois.nic.name` , I tried the `addServer` function like this:

```php
        $servers = $whois->getTldModule()
            ->addServers(TldServer::fromDataList([
                ['zone' => '.name', 'host' => 'whois.namecheap.com'],
                ['zone' => '.name', 'host' => 'whois.nic.name'],
            ]))->matchServers('mhdzaherghaibeh.name');
```

but it just added them to the list without overwriting the order
```
.name whois.nic.name .name whois.namecheap.com .name whois.nic.name 
```

**Comment by linuxjuggler** [comment]
Here is the list of all the registrar IDs from **IANA** https://www.iana.org/assignments/registrar-ids/registrar-ids.xhtml#registrar-ids-1

**Comment by linuxjuggler** [comment]
No need to waste your time on it too much, it's just an idea I got in my head. but not worth wasting a lot of time on it.

**Comment by io-developer** [comment]
Agree.
But this https://www.iana.org/assignments/registrar-ids/registrar-ids.xhtml#registrar-ids-1 is very interesting

I want to find something like this (query TLD info from whois) but for registrar ID
`whois com -h whois.iana.org`
```
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

domain:       COM

organisation: VeriSign Global Registry Services
address:      12061 Bluemont Way
address:      Reston Virginia 20190
address:      United States

contact:      administrative
name:         Registry Customer Service
organisation: VeriSign Global Registry Services
address:      12061 Bluemont Way
address:      Reston Virginia 20190
address:      United States
phone:        +1 703 925-6999
fax-no:       +1 703 948 3978
e-mail:       info@verisign-grs.com

contact:      technical
name:         Registry Customer Service
organisation: VeriSign Global Registry Services
address:      12061 Bluemont Way
address:      Reston Virginia 20190
address:      United States
phone:        +1 703 925-6999
fax-no:       +1 703 948 3978
e-mail:       info@verisign-grs.com

nserver:      A.GTLD-SERVERS.NET 192.5.6.30 2001:503:a83e:0:0:0:2:30
nserver:      B.GTLD-SERVERS.NET 192.33.14.30 2001:503:231d:0:0:0:2:30
nserver:      C.GTLD-SERVERS.NET 192.26.92.30 2001:503:83eb:0:0:0:0:30
nserver:      D.GTLD-SERVERS.NET 192.31.80.30 2001:500:856e:0:0:0:0:30
nserver:      E.GTLD-SERVERS.NET 192.12.94.30 2001:502:1ca1:0:0:0:0:30
nserver:      F.GTLD-SERVERS.NET 192.35.51.30 2001:503:d414:0:0:0:0:30
nserver:      G.GTLD-SERVERS.NET 192.42.93.30 2001:503:eea3:0:0:0:0:30
nserver:      H.GTLD-SERVERS.NET 192.54.112.30 2001:502:8cc:0:0:0:0:30
nserver:      I.GTLD-SERVERS.NET 192.43.172.30 2001:503:39c1:0:0:0:0:30
nserver:      J.GTLD-SERVERS.NET 192.48.79.30 2001:502:7094:0:0:0:0:30
nserver:      K.GTLD-SERVERS.NET 192.52.178.30 2001:503:d2d:0:0:0:0:30
nserver:      L.GTLD-SERVERS.NET 192.41.162.30 2001:500:d937:0:0:0:0:30
nserver:      M.GTLD-SERVERS.NET 192.55.83.30 2001:501:b1f9:0:0:0:0:30
ds-rdata:     30909 8 2 E2D3C916F6DEEAC73294E8268FB5885044A833FC5459588F4A9184CFC41A5766

whois:        whois.verisign-grs.com

status:       ACTIVE
remarks:      Registration information: http://www.verisigninc.com

created:      1985-01-01
changed:      2017-10-05
source:       IANA

```

**Comment by io-developer** [comment]
> I'll look to see if I can find something here.
> 
> Also, what is the way to push `whois.namecheap.com` to be before `whois.nic.name` , I tried the `addServer` function like this:
> 
> ```
>         $servers = $whois->getTldModule()
>             ->addServers(TldServer::fromDataList([
>                 ['zone' => '.name', 'host' => 'whois.namecheap.com'],
>                 ['zone' => '.name', 'host' => 'whois.nic.name'],
>             ]))->matchServers('mhdzaherghaibeh.name');
> ```
> 
> but it just added them to the list without overwriting the order
> 
> ```
> .name whois.nic.name .name whois.namecheap.com .name whois.nic.name 
> ```

I think you have to
* get all current to local array via `getServers()`
* find `.name` and place custom before
* override all by `setServers($yourModifiedServerList)`

**Comment by linuxjuggler** [comment]
> > I'll look to see if I can find something here.
> > Also, what is the way to push `whois.namecheap.com` to be before `whois.nic.name` , I tried the `addServer` function like this:
> > ```
> >         $servers = $whois->getTldModule()
> >             ->addServers(TldServer::fromDataList([
> >                 ['zone' => '.name', 'host' => 'whois.namecheap.com'],
> >                 ['zone' => '.name', 'host' => 'whois.nic.name'],
> >             ]))->matchServers('mhdzaherghaibeh.name');
> > ```
> > 
> > 
> > but it just added them to the list without overwriting the order
> > ```
> > .name whois.nic.name .name whois.namecheap.com .name whois.nic.name 
> > ```
> 
> I think you have to
> 
>     * get all current to local array via `getServers()`
> 
>     * find `.name` and place custom before
> 
>     * override all by `setServers($yourModifiedServerList)`

that's exactly what I am doing right now and this is why I have deleted my comment ;)

**Pull request merged**
