### PR TITLE
DateHelper: trim only if scalar (fixes #153)

### LINKED ISSUE #153: TypeError: trim()
**PHP-Whois version**: 4.1.0

**PHP version**: 8.0.7

**Description**  
I got an error which you can see below:
TypeError: trim(): Argument #1 ($string) must be of type string, array given in file C:\xampp\x\x\vendor\io-developer\php-whois\src\Iodev\Whois\Helpers\DateHelper.php on line 14

**How to reproduce**  
just test domain availability on asdfghj.com

### PR DESCRIPTION
**Pull request by kornrunner**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #153
| License       | MIT

Trim can only be applied to scalars / fixes #153

### CODE REVIEW

**Comment by io-developer** [comment]
Not exactly.
First of all: needed to reproduce and understand the reason why there is array instead of string.
I guess it's some sort of bug in GroupSelector

**Comment by io-developer** [comment]
image

**Comment by kornrunner** [comment]
During `GroupSelector->mapUnixTime` `DateHelper` gets called against stuff all items (which happen to be empty arrays, arrays with dates and arrays with random data), and some might be nested (as in #153):

```
  ["Domain Status"]=>
  array(2) {
    [0]=>
    string(71) "clientTransferProhibited https://icann.org/epp#clientTransferProhibited"
    [1]=>
    string(27) "ok https://icann.org/epp#ok"
  }
```

I don't see a change in other method return values, but I'm open to suggestions. Thanks!

**Comment by io-developer** [comment]
Some parsing improvements needed. Wrong data fields using as date..

**Comment by io-developer** [comment]
Fixed in your style, but on upper level - https://github.com/io-developer/php-whois/commit/f7ea1437e413007f93eb4299763b3726163defb8

**Pull request closed without merging**
