### PR TITLE
Add support for .ar domains

### PR DESCRIPTION
**Pull request by bessone**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes   
| License       | MIT

Added whois server for .ar domains.

### CODE REVIEW

**Comment by io-developer** [comment]
image
Looks like first coomit was merged. And second is unexisting dev branch?..
Could you rebase from latest master branch? I guess only one commit should remain 'Add whois for .ar'

**Comment by bessone** [comment]
Yeah sorry, it's Monday morning, my brain wasn't on yet.
Later I correct the mess of the various branches and update :-D

**Comment by io-developer** [comment]
Ok, I got it :)

**Comment by bessone** [comment]
Done! (and sorry again, but i still make some mess with GIT)

**Comment by io-developer** [comment]
included to unit test with some fixes - https://github.com/io-developer/php-whois/commit/efcc7aecc32169bf798de02c6e0fa23c9999c122

**Pull request merged**
