### PR TITLE
Update SocketLoader.php

### PR DESCRIPTION
**Pull request by stefanmcds-mnt**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT

### CODE REVIEW

**Comment by io-developer** [comment]
Hi
Could you check your changes doesn't break a case №2 in this merged PR https://github.com/io-developer/php-whois/pull/136?

https://github.com/io-developer/php-whois/pull/136/files#diff-c138cf4c619cd6f4351e09500e4177f5108209d51e4b161fb081df5fe6d4163fR70

**Comment by io-developer** [comment]
By the way this code always be false :)

**Comment by stefanmcds-mnt** [comment]
With (FALSE === $chunk || $chunk === '') i have  error Response chunk cannot be read with most gTLD and ccTLD. Change FALSE === $chunk && $chunk === '') i have righth response from gTLD and ccTLD.

**Comment by io-developer** [comment]
Try just `if (false === $chunk)`. I guess it will work for you

**Comment by io-developer** [comment]
Merged fix https://github.com/io-developer/php-whois/pull/154 into master. Now it should work

**Pull request closed without merging**
